# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 813fbf314f53eef3dda539c81608cbab1812c079bb73d1ce496b431dadaf7685ea25e5fce8cef8dd2b3b0202c7e7401895b01ab4a070c4ce18b8768ee007bff6

test:
  secret_key_base: 4272fd96c85c7dea059784f2a323d52392c0a177e1945a43e5ec6188d11729057aad2a5c1406325d5b9daa9ed1484f6fed94507bb874efdd0c9ab2a3aeacb77c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
